### ISSUE TITLE
device trigger.

### ISSUE THREAD

**Issue by dezral** [perbrage/node-red-contrib-telldus-zwave-v2-local#4]
thanks for this plugin, it works well.. but i can't get access to all of my devices.. i have a motion(433) sensor that is seen as a switch on/off by telldus.. and that cant be used in node-red..

i would love a device output "switch device" node, so i can trigger someting in node-red when my on/off switch is triggered.. let say my motion sensor(switch) is on. then every 5 sec i collect from telldus local if it on or not and then trigger my "welcome" sceen ,-).

**Comment by perbrage** [comment]
Hi!

That kind of device should turn up under the switch-sensor node, where you can check at intervals and send messages if it changes.

If you can not find your device it may be because I filter the devices depending on their type. If you run a curl against your Telldus Gateway, and if it set up correctly, you would find a local ID for your 433 device. You can add that manually on the switch-sensor and give it any name you want. You don't have to use the drop down I provide.

**Comment by dezral** [comment]
so true  ;-) it works.. thx

it a proove 433 motion sensor with this output via curl.
{
  "device": [
    {
      "id": 9,
      "methods": 3,
      "name": "Motion Stuen",
      "state": 1,
      "statevalue": "",
      "type": "device"
    },

**Comment by perbrage** [comment]
Can I close this issue?

**Comment by dezral** [comment]
yes
